variables:
    LATEST_VER : batlefroc/akau:latest
    CURRENT_VER: batlefroc/akau:1.1
    CONTAINER_NAME: akau
include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
    stage: test
    artifacts:
        paths: [gl-code-quality-report.json]

stages:
    - lint
    - build
    - StopOld
    - run
    - hook
    - test

StopOld: #Permet de stoper un container qui fonctionne déja
    image: docker:latest
    stage: StopOld
    allow_failure: true
    tags: 
        - kimsufi
    needs:
        - Build
    script:
        - docker container stop $CONTAINER_NAME
        - docker container rm $CONTAINER_NAME
Build: #Permet de l'image Dockerfile
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker info
    tags: 
        - kimsufi
    stage: build
    script:
        - docker build -t $LATEST_VER -t $CURRENT_VER .
Run: #Permet de Start le container
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker info
    tags: 
        - kimsufi
    stage: run
    needs:
        - Build
    script : 
        - docker run -d --network weebo --name $CONTAINER_NAME -p 8081:8080 $LATEST_VER
Lint: #Permet de noter le code
    stage: lint
    image: node:latest
    allow_failure: true
    tags: 
        - kimsufi
    script:
        - npm install -g eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y  eslint-plugin-prettier eslint-plugin-react
        - npm install
        - eslint ./src/
Curl: #Déclenche le webhook discord qui dis que le launch est finis
    stage: hook
    image: docker:git
    allow_failure: true
    tags: 
        - kimsufi
    needs:
        - Run
    script:
        - apk update
        - apk add curl
        - export PROJECT_URL="$CI_PIPELINE_URL"
        - export USER_START="$GITLAB_USER_LOGIN	"
        - sh ./deploy.sh
