variables:
    LATEST_VER : batlefroc/akau:latest
    CURRENT_VER: batlefroc/akau:1.1
    CONTAINER_NAME: akau

stages:
    - lint
    - build
    - StopOld
    - run
    - hook

StopOld: #Permet de stoper un container qui fonctionne déja
  image: docker:latest
  stage: StopOld
  allow_failure: true
  script:
    - docker container stop $CONTAINER_NAME
    - docker container rm $CONTAINER_NAME
Build: #Permet de l'image Dockerfile
    image: docker:latest
    services:
    - docker:dind
    before_script:
    - docker info
    stage: build
    script:
        - docker build -t $LATEST_VER -t $CURRENT_VER .
Run: #Permet de Start le container
    image: docker:latest
    services:
    - docker:dind
    before_script:
    - docker info
    stage: run
    script : 
        - docker run -d --network weebo --name $CONTAINER_NAME -p 8081:8080 $LATEST_VER
Lint: #Permet de noter le code
    stage: lint
    image: node:latest
    allow_failure: true
    script:
        - npm install -g eslint eslint-config-airbnb eslint-config-prettier eslint-plugin-flowtype eslint-plugin-import eslint-plugin-jsx-a11y  eslint-plugin-prettier eslint-plugin-react
        - npm install
        - eslint ./src/
Curl: #Déclenche le webhook discord qui dis que le launch est finis
    stage: hook
    image: docker:git
    allow_failure: true
    script:
        - apt-get install curl git
        - export PROJECT_URL="$CI_PROJECT_URL"
        - export USER_START="$GITLAB_USER_LOGIN	"
        - sh ./deploy.sh